ERROR = "‼"  # Error
WAIT = "⏳"  # Wait
FINISH = "🏁"  # Finished
NOTIFY = "🔔"  # Notify
CANCEL = "❌"  # Cancel
TOP = "👍"  # Yes
DOWN = "👎"  # No
DONE = "✔"  # Done
FAILED = "✖"  # Failed
GOODBYE = "👋"  # Goodbye
QUESTION = "❓"  # Question
MONEY = "💰"  # Trade
DIAMOND = "💎"  # Balance
LIST = "📒"  # Orders
FLASH = "⚡"  # Ticker
HANDSHAKE = "🤝"  # Trades
CHART = "📊"  # Chart
STARS = "✨"  # Stats
ROBOT = "🤖"  # Bot
LINK = "🔗"  # Pair
SPEECH = "💬"  # Feedback
INFO = "ℹ"  # Info / Help
CHECK = "✅"  # Done
BULLETPOINT = "🔹"  # Bulletpoint
OH_NO = "☹"  # No data
